In [1]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
# to count the number of spam and ham in the given dataset 
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [8]:
df.shape

(5572, 2)

In [9]:
# you can also create a function to overcome the use of lamda function
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [10]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [13]:
X_train.shape

(4457,)

In [14]:
X_test.shape

(1115,)

In [15]:
type(X_train)

pandas.core.series.Series

In [16]:
X_train[:4]

4556    7 wonders in My WORLD 7th You 6th Ur style 5th...
220     Yeah you should. I think you can use your gt a...
2851    She's fine. Good to hear from you. How are you...
1886    I think asking for a gym is the excuse for laz...
Name: Message, dtype: object

In [17]:
type(y_train)

pandas.core.series.Series

In [18]:
y_train[:4]

4556    0
220     0
2851    0
1886    0
Name: spam, dtype: int64

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7702 sparse matrix of type '<class 'numpy.int64'>'
	with 59621 stored elements in Compressed Sparse Row format>

In [20]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [21]:
X_train_cv.shape

(4457, 7702)

In [30]:
v.get_feature_names_out().shape

(7702,)

In [27]:
v.get_feature_names_out()[1000:1050]

array(['apologetic', 'apologise', 'apology', 'app', 'apparently',
       'appeal', 'appendix', 'applausestore', 'applebees', 'apples',
       'application', 'apply', 'applying', 'appointment', 'appointments',
       'appreciate', 'appreciated', 'approaching', 'approve', 'approved',
       'approx', 'apps', 'appt', 'appy', 'april', 'apt', 'aptitude',
       'aquarius', 'ar', 'arab', 'arabian', 'arcade', 'ard', 'are',
       'area', 'aren', 'arent', 'arestaurant', 'aretaking',
       'areyouunique', 'argentina', 'argh', 'argue', 'arguing',
       'argument', 'arguments', 'aries', 'arise', 'arises', 'arithmetic'],
      dtype=object)

In [23]:
v.vocabulary_

{'wonders': 7540,
 'in': 3604,
 'my': 4610,
 'world': 7555,
 '7th': 638,
 'you': 7663,
 '6th': 611,
 'ur': 7149,
 'style': 6491,
 '5th': 573,
 'smile': 6195,
 '4th': 532,
 'personality': 5119,
 '3rd': 474,
 'nature': 4654,
 '2nd': 407,
 'sms': 6204,
 'and': 951,
 '1st': 336,
 'lovely': 4176,
 'friendship': 2984,
 'good': 3169,
 'morning': 4530,
 'dear': 2166,
 'yeah': 7635,
 'should': 6064,
 'think': 6795,
 'can': 1611,
 'use': 7164,
 'your': 7669,
 'gt': 3237,
 'atm': 1109,
 'now': 4792,
 'to': 6882,
 'register': 5605,
 'not': 4778,
 'sure': 6569,
 'but': 1559,
 'if': 3566,
 'there': 6781,
 'anyway': 991,
 'help': 3374,
 'let': 4036,
 'me': 4353,
 'know': 3911,
 'when': 7438,
 'do': 2351,
 'be': 1261,
 'are': 1033,
 'ready': 5542,
 'she': 6015,
 'fine': 2836,
 'hear': 3351,
 'from': 2997,
 'how': 3485,
 'happy': 3310,
 'new': 4708,
 'year': 7636,
 'oh': 4861,
 'asking': 1081,
 'for': 2924,
 'gym': 3260,
 'is': 3705,
 'the': 6763,
 'excuse': 2675,
 'lazy': 3995,
 'people': 5099,
 'jog'

In [24]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [25]:
np.where(X_train_np[0]!=0)

(array([ 336,  407,  474,  532,  573,  611,  638,  951, 2166, 2984, 3169,
        3604, 4176, 4530, 4610, 4654, 5119, 6195, 6204, 6491, 7149, 7540,
        7555, 7663], dtype=int64),)

In [31]:
dir(v)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',

In [33]:
X_train[:4][4556]

'7 wonders in My WORLD 7th You 6th Ur style 5th Ur smile 4th Ur Personality 3rd Ur Nature 2nd Ur SMS and 1st "Ur Lovely Friendship"... good morning dear'

Train the naive bayes model

In [34]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [35]:
X_test_cv = v.transform(X_test)

In [37]:
# whenever you have imbalance dataset you need to see the classification report 
# here we had very less number of span in comparison to hame
from sklearn.metrics import classification_report
y_pred = model.predict(X_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       965
           1       0.98      0.92      0.95       150

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [38]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

Train the model using sklearn pipeline and reduce number of lines of code

In [39]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [40]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [41]:
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       965
           1       0.98      0.92      0.95       150

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

